In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import time, random, re
import requests
from bs4 import BeautifulSoup
import openpyxl
import pandas as pd
import numpy as np

In [ ]:
#도로명주소 안내시스템 사이트를 통한 도로명주소 -> 지번주소 변환

def doro_to_jibun(keyword):
    url = f"https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword={keyword}&dsgubuntext=&dscity1text=&dscounty1text=&dsemd1text=&dsri1text=&dssan1text=&dsrd_nm1text="
    req = requests.get(url)
    soup = BeautifulSoup(req.text, "html.parser")
    soup1 = soup.select('#searchAddress > div.container.support_search_list > div.search_list > ol > li')
    
    if len(soup1)==0:  # 도로명주소를 검색했을 때 결과가 나오지 않는다면
        return np.nan
    else:
        jibun_juso = soup1[0].find('div', class_='subejct_2').find('span', class_='roadNameText').text
        jibun = re.sub('&nbsp;|\t|\r|\n', '', jibun_juso).strip().replace('  ', ' ')

        time.sleep(0.5)
        return jibun

## 관광안내소

In [ ]:
info = pd.read_csv('/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/부산관광안내소.csv', encoding = 'cp949')

In [ ]:
info.head()

,콘텐츠ID,전화번호,운영시간,위도,경도,이름,주소,외국어안내,소개
0,1,051-743-2322,09:00~10:00,35.156017,129.18184,-,-,-,-
1,2,051-522-0303,09:00~18:00,35.203190,129.08539,동래구관광안내소,부산광역시 동래구 명륜로112번길 46,중국어 안내 가능,동래구관광안내소 운영시간 : 3월 ~ 10월
2,3,051-231-0252,09:00~18:00,35.076805,129.01797,서구 관광안내소,서구 송도해변로 100(송도해수욕장),"영어, 중국어 가능","송도해수욕장매주 월 화, 오전 9시~13시 미운영"
3,4,051-254-5504,10:00 ~ 19:00,35.097250,129.03569,중구관광안내소,부산광역시 중구 태종로 8(남포동1가),"영어, 일어, 중국어 가능","2015.5월 개소한 중구관광안내소는 영도대교 입구에 위치하고 있으며, 영어, 일본..."
4,5,051-419-4048,09:00 ~ 18:00,35.094585,129.03874,영도관광안내센터,부산광역시 영도구 봉래나루로 79(봉래동1가),"영어,중국어,몽골어 가능",영도대교 옆에 자리한 관광안내소로 영도대교의 도개하는 모습을 본뜬 독특한 형태의 건...

In [ ]:
# 도로명 주소 결측치 확인 -> 없음
info['주소'].isnull().sum()

0

In [ ]:
info['지번주소'] = 0

In [ ]:
info.head()

,콘텐츠ID,전화번호,운영시간,위도,경도,이름,주소,외국어안내,소개,지번주소
0,1,051-743-2322,09:00~10:00,35.156017,129.18184,-,-,-,-,0
1,2,051-522-0303,09:00~18:00,35.203190,129.08539,동래구관광안내소,부산광역시 동래구 명륜로112번길 46,중국어 안내 가능,동래구관광안내소 운영시간 : 3월 ~ 10월,0
2,3,051-231-0252,09:00~18:00,35.076805,129.01797,서구 관광안내소,서구 송도해변로 100(송도해수욕장),"영어, 중국어 가능","송도해수욕장매주 월 화, 오전 9시~13시 미운영",0
3,4,051-254-5504,10:00 ~ 19:00,35.097250,129.03569,중구관광안내소,부산광역시 중구 태종로 8(남포동1가),"영어, 일어, 중국어 가능","2015.5월 개소한 중구관광안내소는 영도대교 입구에 위치하고 있으며, 영어, 일본...",0
4,5,051-419-4048,09:00 ~ 18:00,35.094585,129.03874,영도관광안내센터,부산광역시 영도구 봉래나루로 79(봉래동1가),"영어,중국어,몽골어 가능",영도대교 옆에 자리한 관광안내소로 영도대교의 도개하는 모습을 본뜬 독특한 형태의 건...,0

In [ ]:
from tqdm import tqdm

In [ ]:
for i in tqdm(range(len(info))):
    keyword = info['주소'][i]
    info['지번주소'][i] = doro_to_jibun(keyword)

  0%|          | 0/25 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
100%|██████████| 25/25 [00:45<00:00,  1.81s/it]

In [ ]:
info.head()

,콘텐츠ID,전화번호,운영시간,위도,경도,이름,주소,외국어안내,소개,지번주소
0,1,051-743-2322,09:00~10:00,35.156017,129.18184,-,-,-,-,NaN
1,2,051-522-0303,09:00~18:00,35.203190,129.08539,동래구관광안내소,부산광역시 동래구 명륜로112번길 46,중국어 안내 가능,동래구관광안내소 운영시간 : 3월 ~ 10월,부산광역시 동래구 수안동 462-6 수안치안센터
2,3,051-231-0252,09:00~18:00,35.076805,129.01797,서구 관광안내소,서구 송도해변로 100(송도해수욕장),"영어, 중국어 가능","송도해수욕장매주 월 화, 오전 9시~13시 미운영",부산광역시 서구 암남동 135-5 송도해수욕장
3,4,051-254-5504,10:00 ~ 19:00,35.097250,129.03569,중구관광안내소,부산광역시 중구 태종로 8(남포동1가),"영어, 일어, 중국어 가능","2015.5월 개소한 중구관광안내소는 영도대교 입구에 위치하고 있으며, 영어, 일본...",부산광역시 중구 남포동1가 33-9 중구 관광안내소
4,5,051-419-4048,09:00 ~ 18:00,35.094585,129.03874,영도관광안내센터,부산광역시 영도구 봉래나루로 79(봉래동1가),"영어,중국어,몽골어 가능",영도대교 옆에 자리한 관광안내소로 영도대교의 도개하는 모습을 본뜬 독특한 형태의 건...,부산광역시 영도구 봉래동1가 1 영도웰컴센터

In [ ]:
info.to_csv("/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/주소변환(시영)/부산관광안내소.csv")

## 우수 숙박 업소

In [ ]:
stay = pd.read_csv('/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/부산광역시 우수숙박업소현황(202106).csv')

In [ ]:
stay.head()

   SKEY STAYNG_BSSH_SE GUGUN_NM                 ADRES    BSSH_NM     CTTPC
0     1           청정숙박      수영구   수영구 광안해변로 155 (광안동)      브릿지모텔  755-0573
1     2           청정숙박      금정구     금정구 청룡예전로 5 (청룡동)        범어장  508-5804
2     3           청정숙박      연제구   연제구 중앙대로 1122 (연산동)      센트럴호텔  866-6225
3     7           청정숙박     해운대구  해운대구 해운대해변로 271 (중동)       MS호텔  741-3838
4     8           청정숙박     해운대구      해운대구 중동1로 41(중동)  게스트하우스 포비  746-7990

In [ ]:
# 도로명 주소 결측치 확인 -> 없음
stay['ADRES'].isnull().sum()

0

In [ ]:
stay['동'] = 0

In [ ]:
stay.head()

   SKEY STAYNG_BSSH_SE GUGUN_NM                 ADRES    BSSH_NM     CTTPC  동
0     1           청정숙박      수영구   수영구 광안해변로 155 (광안동)      브릿지모텔  755-0573  0
1     2           청정숙박      금정구     금정구 청룡예전로 5 (청룡동)        범어장  508-5804  0
2     3           청정숙박      연제구   연제구 중앙대로 1122 (연산동)      센트럴호텔  866-6225  0
3     7           청정숙박     해운대구  해운대구 해운대해변로 271 (중동)       MS호텔  741-3838  0
4     8           청정숙박     해운대구      해운대구 중동1로 41(중동)  게스트하우스 포비  746-7990  0

In [ ]:
import re

In [ ]:
for i in range(len(stay)):
  input_string = stay['ADRES'][i].split()[-1]
  output_string = re.sub(r'[^\w\s]', '', input_string)
  stay['동'][i] = output_string

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
for i in range(len(stay)):
  input_string = stay['동'][i]
  output_string = re.sub(r'[0-9]+', '', input_string)
  stay['동'][i] = output_string

In [ ]:
stay.head()

,SKEY,STAYNG_BSSH_SE,GUGUN_NM,ADRES,BSSH_NM,CTTPC,동
0,1,청정숙박,수영구,수영구 광안해변로 155 (광안동),브릿지모텔,755-0573,광안동
1,2,청정숙박,금정구,금정구 청룡예전로 5 (청룡동),범어장,508-5804,청룡동
2,3,청정숙박,연제구,연제구 중앙대로 1122 (연산동),센트럴호텔,866-6225,연산동
3,7,청정숙박,해운대구,해운대구 해운대해변로 271 (중동),MS호텔,741-3838,중동
4,8,청정숙박,해운대구,해운대구 중동1로 41(중동),게스트하우스 포비,746-7990,중동

In [ ]:
stay.to_csv("/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/주소변환(시영)/부산광역시 우수숙박업소현황(202106).csv")

## 부산쇼핑정보

In [ ]:
shop = pd.read_csv('/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/부산쇼핑정보.csv', encoding = 'cp949')

ParserError: ignored

In [ ]:
shop.head(3)

In [ ]:
# 도로명 주소 결측치 확인 -> 없음
shop['주소'].isnull().sum()

In [ ]:
shop['지번주소'] = 0

In [ ]:
shop.head(3)

In [ ]:
from tqdm import tqdm

In [ ]:
for i in tqdm(range(len(shop))):
    keyword = shop['주소'][i]
    shop['지번주소'][i] = doro_to_jibun(keyword)

In [ ]:
shop.head(3)

In [ ]:
shop.to_csv("/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/주소변환(시영)/부산쇼핑정보.csv")

## 식당 정보

In [ ]:
food = pd.read_csv('/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/부산관광공사_음식테마거리 음식점 기본정보_20220101.csv')

In [ ]:
food.info()
#데이터 수 50512

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50512 entries, 0 to 50511
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   식당(ID)    50512 non-null  int64
 1   식당명       50512 non-null  object
 2   도로명주소     50299 non-null  object
 3   지번주소      50058 non-null  object
 4   식당위도      50512 non-null  float64
 5   식당경도      50512 non-null  float64
 6   식당대표전화번호  39199 non-null  object
 7   영업신고증업태명  43283 non-null  object
 8   영업인허가명    50512 non-null  object
 9   음식점소개내용   50512 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 3.9+ MB

In [ ]:
food.head()

,식당(ID),식당명,도로명주소,지번주소,식당위도,식당경도,식당대표전화번호,영업신고증업태명,영업인허가명,음식점소개내용
0,1086,명지횟집,부산광역시 강서구 신포길17번길 10-1,부산광역시 강서구 명지동 1-440,35.1131,128.9316,051-271-2662,한식,일반음식점,"""명지횟집""은 부산광역시 강서구에 있습니다. 지방자치단체 인증을 받은 농림축산식품부..."
1,1091,용두산식당,부산광역시 중구 대청로126번길 32-6,부산광역시 중구 동광동2가 11-37,35.1002,129.0344,051-245-9626,한식,일반음식점,"부산광역시 중구에서 맛집을 찾으신다면 ""용두산식당""을 추천합니다."
2,1092,섹션,부산광역시 사상구 사상로309번길 16,부산광역시 사상구 덕포동 419-6,35.1725,128.9825,051-302-1735,한식,일반음식점,"부산광역시 사상구에서 어디를 갈지 고민이라면! ""섹션""에 가보시는 건 어떨까요?"
3,1240,흥화반점,부산광역시 부산진구 서전로47번길 52-1,부산광역시 부산진구 전포동 637-5,35.1602,129.0649,051-809-3202,중국식,일반음식점,"부산광역시 부산진구에서 맛집을 찾으신다면 ""흥화반점""에 방문해보세요. 부전역 근처에..."
4,1266,하동집,부산광역시 서구 구덕로124번길 59-1,부산광역시 서구 토성동1가 14-3,35.0994,129.0226,051-257-3081,한식,일반음식점,"부산광역시 서구에서 식당을 찾으신다면? ""하동집""을 방문해보세요! 50년 이상의 전..."

In [ ]:
# 지번주소 결측치 확인 -> 454개 
food['지번주소'].isnull().sum()

454

In [ ]:
# 지번주소 결측치 있는 행 제거
# 남은 데이터 수 50512 - 454 = 50058
food_1 = food.dropna(subset=['지번주소'])
food_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50058 entries, 0 to 50511
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   식당(ID)    50058 non-null  int64
 1   식당명       50058 non-null  object
 2   도로명주소     49845 non-null  object
 3   지번주소      50058 non-null  object
 4   식당위도      50058 non-null  float64
 5   식당경도      50058 non-null  float64
 6   식당대표전화번호  39012 non-null  object
 7   영업신고증업태명  42890 non-null  object
 8   영업인허가명    50058 non-null  object
 9   음식점소개내용   50058 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 4.2+ MB

In [ ]:
food_1['동']=food_1['지번주소'].str.split(" ").str[2]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
food_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50058 entries, 0 to 50511
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   식당(ID)    50058 non-null  int64
 1   식당명       50058 non-null  object
 2   도로명주소     49845 non-null  object
 3   지번주소      50058 non-null  object
 4   식당위도      50058 non-null  float64
 5   식당경도      50058 non-null  float64
 6   식당대표전화번호  39012 non-null  object
 7   영업신고증업태명  42890 non-null  object
 8   영업인허가명    50058 non-null  object
 9   음식점소개내용   50058 non-null  object
 10  동         50055 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 4.6+ MB

In [ ]:
food_1.head(10)

,식당(ID),식당명,도로명주소,지번주소,식당위도,식당경도,식당대표전화번호,영업신고증업태명,영업인허가명,음식점소개내용,동
0,1086,명지횟집,부산광역시 강서구 신포길17번길 10-1,부산광역시 강서구 명지동 1-440,35.1131,128.9316,051-271-2662,한식,일반음식점,"""명지횟집""은 부산광역시 강서구에 있습니다. 지방자치단체 인증을 받은 농림축산식품부...",명지동
1,1091,용두산식당,부산광역시 중구 대청로126번길 32-6,부산광역시 중구 동광동2가 11-37,35.1002,129.0344,051-245-9626,한식,일반음식점,"부산광역시 중구에서 맛집을 찾으신다면 ""용두산식당""을 추천합니다.",동광동2가
2,1092,섹션,부산광역시 사상구 사상로309번길 16,부산광역시 사상구 덕포동 419-6,35.1725,128.9825,051-302-1735,한식,일반음식점,"부산광역시 사상구에서 어디를 갈지 고민이라면! ""섹션""에 가보시는 건 어떨까요?",덕포동
3,1240,흥화반점,부산광역시 부산진구 서전로47번길 52-1,부산광역시 부산진구 전포동 637-5,35.1602,129.0649,051-809-3202,중국식,일반음식점,"부산광역시 부산진구에서 맛집을 찾으신다면 ""흥화반점""에 방문해보세요. 부전역 근처에...",전포동
4,1266,하동집,부산광역시 서구 구덕로124번길 59-1,부산광역시 서구 토성동1가 14-3,35.0994,129.0226,051-257-3081,한식,일반음식점,"부산광역시 서구에서 식당을 찾으신다면? ""하동집""을 방문해보세요! 50년 이상의 전...",토성동1가
5,1268,묘향정,부산광역시 영도구 청학로6번길 4,부산광역시 영도구 청학동 120-85,35.0909,129.0628,051-416-0086,중국식,일반음식점,"부산광역시 영도구에서 가 볼 만한 식당을 찾으신다면? ""묘향정""을 추천합니다! 50...",청학동
6,1350,중화각,부산광역시 동구 망양로689번길 10,부산광역시 동구 수정동 1171-8,35.1274,129.0403,051-467-1312,중국식,일반음식점,"어디 가야 할지 고민이시라고요? 그럼 부산광역시 동구 맛집, ""중화각""을 추천합니다...",수정동
7,1351,밀양보신탕,부산광역시 동구 중앙대로361번길 36-3,부산광역시 동구 수정동 283-4,35.1291,129.0462,051-467-3635,한식,일반음식점,"무엇을 먹을지 고민되신다고요? 부산광역시 동구에 계시다면 ""밀양보신탕""을 추천합니다...",수정동
8,1352,만춘반점,NaN,부산광역시 동구 범일동 311-1,35.1356,129.0594,051-646-5057,중국식,일반음식점,"어디 가야 할지 고민이시라고요? 그럼 부산광역시 동구 맛집, ""만춘반점""을 추천합니...",범일동
9,1353,덕화원,부산광역시 동구 진성로 8-1,부산광역시 동구 수정동 1-105,35.1298,129.0486,051-441-8807,중국식,일반음식점,"부산광역시 동구에 가신다면 ""덕화원""에 방문해보세요~ 50년 이상의 전통을 자랑합니다.",수정동

In [ ]:
# 숫자 공백으로 변경
food_1['동'] = food_1['동'].str.replace(pat=r'[0-9]+',repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('2가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('3가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('4가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('5가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('6가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('7가', repl=r'',regex=True)
food_1['동'] = food_1['동'].str.replace('8가', repl=r'',regex=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [ ]:
food_1.head()

,식당(ID),식당명,도로명주소,지번주소,식당위도,식당경도,식당대표전화번호,영업신고증업태명,영업인허가명,음식점소개내용,동
0,1086,명지횟집,부산광역시 강서구 신포길17번길 10-1,부산광역시 강서구 명지동 1-440,35.1131,128.9316,051-271-2662,한식,일반음식점,"""명지횟집""은 부산광역시 강서구에 있습니다. 지방자치단체 인증을 받은 농림축산식품부...",명지동
1,1091,용두산식당,부산광역시 중구 대청로126번길 32-6,부산광역시 중구 동광동2가 11-37,35.1002,129.0344,051-245-9626,한식,일반음식점,"부산광역시 중구에서 맛집을 찾으신다면 ""용두산식당""을 추천합니다.",동광동
2,1092,섹션,부산광역시 사상구 사상로309번길 16,부산광역시 사상구 덕포동 419-6,35.1725,128.9825,051-302-1735,한식,일반음식점,"부산광역시 사상구에서 어디를 갈지 고민이라면! ""섹션""에 가보시는 건 어떨까요?",덕포동
3,1240,흥화반점,부산광역시 부산진구 서전로47번길 52-1,부산광역시 부산진구 전포동 637-5,35.1602,129.0649,051-809-3202,중국식,일반음식점,"부산광역시 부산진구에서 맛집을 찾으신다면 ""흥화반점""에 방문해보세요. 부전역 근처에...",전포동
4,1266,하동집,부산광역시 서구 구덕로124번길 59-1,부산광역시 서구 토성동1가 14-3,35.0994,129.0226,051-257-3081,한식,일반음식점,"부산광역시 서구에서 식당을 찾으신다면? ""하동집""을 방문해보세요! 50년 이상의 전...",토성동

In [ ]:
### 돌리지 말것!!!!!!!!
for i in range(len(food_1['동'])):
  try:
    a = food_1['동'][i].split()
    b = a[0]
    food_1['동'][i] = b
  except:
    continue

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [ ]:
food_1.to_csv("/content/drive/Shareddrives/[YBIGTA] Data Analytics Team/시니어 팀 프로젝트/1차 프로젝트/[2팀] 문화재청 공공빅데이터 활용 경진대회/데이터셋/친화도/주소변환(시영)/부산관광공사_음식테마거리 음식점 기본정보_20220101.csv")

In [ ]:
def add_trans(keyword):
    url = f"https://www.juso.go.kr/support/AddressMainSearch.do?searchKeyword={keyword}&dsgubuntext=&dscity1text=&dscounty1text=&dsemd1text=&dsri1text=&dssan1text=&dsrd_nm1text="
    req = requests.get(url)
    soup = BeautifulSoup(req.text, "html.parser")
    soup1 = soup.select('#searchAddress > div.container.support_search_list > div.search_list > ol > li')
    
    if len(soup1)==0:  # 도로명주소를 검색했을 때 결과가 나오지 않을 시
        return np.nan
    else:
        jibun_adr = soup1[0].find('div', class_='subejct_2').find('span', class_='roadNameText').text
        jibun = re.sub('&nbsp;|\t|\r|\n', '', jibun_adr).strip().replace('  ', ' ')

        time.sleep(0.5)
        return jibun